sudo: require
service:
  - docker

before_install:
  - docker build -t igdeveloper/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true igdeveloper/react-test npm test

after_success:
  - docker build -t igdeveloper/multi-client ./client
  - docker build -t igdeveloper/multi-nginx ./nginx
  - docker build -t igdeveloper/multi-server ./server
  - docker build -t igdeveloper/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push igdeveloper/multi-client
  - docker push igdeveloper/multi-nginx
  - docker push igdeveloper/multi-server
  - docker push igdeveloper/multi-worker